### ISSUE TITLE
how to use this plugin?

### ISSUE THREAD

**Issue by qingtian0622** [zyrouge/dart_protocol_registry#1]
eg  http://racconcity//invite?rid=257#target=out

how to  define the scheme 
`final ProtocolScheme scheme = ProtocolScheme(
  appName: 'Test App',
  scheme: 'some-thing-that-doesnt-exist',
  appPath: Platform.resolvedExecutable,
);`

and how to listen the callback?

**Comment by zyrouge** [comment]
I'm not sure if it works with `http`s, but the plugin can be use to create custom schemes like creating `chrome://`. And the class doesn't do anything, you should use the methods to actually create one. All the methods return a future with a value or `void`.

**Comment by qingtian0622** [comment]
> se to create custom schemes l

for example，I have a url like "http://racconcity//invite?rid=257#target=out",how can i use your plugin to define the scheme,I don't know how to use in flutter project, your example is too simple to learn~

**Comment by zyrouge** [comment]
> > se to create custom schemes l
> 
> for example，I have a url like "[http://racconcity//invite?rid=257#target=out",how](http://racconcity//invite?rid=257#target=out%22,how) can i use your plugin to define the scheme,I don't know how to use in flutter project, your example is too simple to learn~

I'm not sure about using `https://` but you can create something like `racconcity://invite?rid=257...` (scheme is `racconcity`) with this.

**Comment by qingtian0622** [comment]
> racconcity

like `final ProtocolScheme scheme = ProtocolScheme(
  appName: 'hxs',
  scheme: 'racconcity',
  appPath: Platform.resolvedExecutable,
);` ?

and how to get the params

**Comment by zyrouge** [comment]
> > racconcity
> 
> like `final ProtocolScheme scheme = ProtocolScheme( appName: 'hxs', scheme: 'racconcity', appPath: Platform.resolvedExecutable, );` ?
> 
> and how to get the params

You can only register schemes. Currently flutter will create another instance of the app, so you should find a way to handle those. Fyi, the `args` from the `main` functions contains the link.

**Comment by qingtian0622** [comment]
> 



> You can only register schemes. Currently flutter will create another instance of the app, so you should find a way to handle those. Fyi, the `args` from the `main` functions contains the link.

where should I use the main method   ,   `Future<void> main(List<String> args) async {
  /** Get the registry */
  final ProtocolRegistryModel registry = getRegistry();

  /** Query */
  await registry.find(scheme);
  await registry.exists(scheme);

  /** Add */
  await registry.add(scheme);

  /** Remove */
  await registry.remove(scheme);
}`

**Comment by zyrouge** [comment]
> > 
> 
> > You can only register schemes. Currently flutter will create another instance of the app, so you should find a way to handle those. Fyi, the `args` from the `main` functions contains the link.
> 
> where should I use the main method , `Future main(List args) async { /** Get the registry */ final ProtocolRegistryModel registry = getRegistry();
> 
> /** Query */ await registry.find(scheme); await registry.exists(scheme);
> 
> /** Add */ await registry.add(scheme);
> 
> /** Remove */ await registry.remove(scheme); }`

https://dart.dev/guides/language/language-tour#the-main-function

**Comment by zyrouge** [comment]
Again, you should handle those arguments. This package will only set the protocol pointing to your app path.

**Comment by qingtian0622** [comment]
> Again, you should handle those arguments. This package will only set the protocol pointing to your app path.

this is my main method.

`void main() {
  Global.init(() {
    ApiConfig.env=ServerEnv.Product;
  });
}`

now I should change it like your main method. is ok?

**Comment by qingtian0622** [comment]
`import 'dart:io';

import 'package:flutter_hxs_win/base/global.dart';
import 'package:flutter_hxs_win/net/api_config.dart';
import 'package:protocol_registry/platforms/model.dart';
import 'package:protocol_registry/protocol_registry.dart';

final ProtocolScheme scheme = ProtocolScheme(
  appName: 'hxs',
  scheme: 'racconcity',
  appPath: Platform.resolvedExecutable,
);


Future<void> main(List<String> args) async {
  /** Get the registry */
  final ProtocolRegistryModel registry = getRegistry();

  /** Query */
  await registry.find(scheme);
  await registry.exists(scheme);

  /** Add */
  await registry.add(scheme);

  /** Remove */
  await registry.remove(scheme);

  Global.init(() {
    ApiConfig.env=ServerEnv.Product;
  });
}`

**Comment by zyrouge** [comment]
> `import 'dart:io';
> 
> import 'package:flutter_hxs_win/base/global.dart'; import 'package:flutter_hxs_win/net/api_config.dart'; import 'package:protocol_registry/platforms/model.dart'; import 'package:protocol_registry/protocol_registry.dart';
> 
> final ProtocolScheme scheme = ProtocolScheme( appName: 'hxs', scheme: 'racconcity', appPath: Platform.resolvedExecutable, );
> 
> Future main(List args) async { /** Get the registry */ final ProtocolRegistryModel registry = getRegistry();
> 
> /** Query */ await registry.find(scheme); await registry.exists(scheme);
> 
> /** Add */ await registry.add(scheme);
> 
> /** Remove */ await registry.remove(scheme);
> 
> Global.init(() { ApiConfig.env=ServerEnv.Product; }); }`

That's up to you. You don't need to copy the code exactly.
